In [1]:
import numpy as np
import pandas as pd

## `pandas.series`
- 굳이 생성해서 쓸 일은 거의 없음
- pandas의 기본 객체 중 하나
- numpy의 ndarray를 기반으로 인덱싱 기능을 추가하여 1차원 배열을 나타냄
- index를 지정하지 않을 시, ndarray와 같이 0-based 인덱스 생성, 지정할 경우 명시적으로 지정된 index를 사용
- 같은 타입의 0개 이상의 데이터를 가질 수 있음

- data로만 생성하기
    - index는 기본적으로 0부터 자동적으로 생성

In [2]:
s1 = pd.Series([1, 2, 3])
s1

0    1
1    2
2    3
dtype: int64

In [3]:
s2 = pd.Series(['a', 'b', 'c'])
s2

0    a
1    b
2    c
dtype: object

In [5]:
s3 = pd.Series(np.arange(200))
s3

0        0
1        1
2        2
3        3
4        4
      ...
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int64

- data, index 함께 명시하기

In [7]:
s4 = pd.Series([1,2,3], [100, 200, 300])
s4

100    1
200    2
300    3
dtype: int64

In [8]:
s5 = pd.Series([1, 2, 3], ['a', 'm', 'k'])
s5

a    1
m    2
k    3
dtype: int64

- data, index, dtype 함께 명시하기
    - dtype은 명시하지 않으면 pandas가 알아서 os와 입력한 데이터 타입에 맞게 유추한다

In [9]:
s6 = pd.Series(np.arange(5), np.arange(100,105), dtype=np.int32)
s6

100    0
101    1
102    2
103    3
104    4
dtype: int32

### 인덱스 활용하기

In [10]:
s6.index

Index([100, 101, 102, 103, 104], dtype='int64')

In [11]:
s6.values

array([0, 1, 2, 3, 4], dtype=int32)

In [12]:
s6[0] # Error

KeyError: 0

1. 인덱스를 통한 데이터 접근

In [13]:
s6[104]

4

2. 인덱스를 통한 데이터 업데이트
- 업데이트의 경우, 인덱스가 존재하지 않으면 주어진 인덱스로 하는 데이터 생성

In [14]:
s6[104] = 70
s6

100     0
101     1
102     2
103     3
104    70
dtype: int32

In [15]:
s6[200] = 80
s6

100     0
101     1
102     2
103     3
104    70
200    80
dtype: int32

3. 인덱스 재사용하기

In [17]:
s7 = pd.Series(np.arange(6), s6.index)
s7

100    0
101    1
102    2
103    3
104    4
200    5
dtype: int64

# Series 데이터 심플 분석(개수, 빈도 등 계산하기)

## Series `size`, `shape`, `unique`, `count`, `value_counts` 함수
- `size`: 개수 반환
- `shape`: 튜플 형태로 shape 반환
- `unique`: 유일한 값만 ndarray로 반환
- `count`: NaN을 제외한 개수를 반환
- `mean`: NaN을 제외한 평균
- `value_counts`: NaN을 제외하고 각 값들의 빈도를 반환

In [18]:
s = pd.Series([1,1,2,1,2,2,2,1,1,3, 3, 4, 5, 5, 7, np.NaN])
s

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [19]:
len(s)

16

In [20]:
s.size

16

In [21]:
s.shape

(16,)

In [22]:
s.unique()

array([ 1.,  2.,  3.,  4.,  5.,  7., nan])

In [23]:
s.count()

15

In [26]:
a = np.array([2, 2, 2, 2, np.NaN]) # ndarray -> NaN이 있으면 연산 불가
a.mean()

nan

In [24]:
s.mean()

2.6666666666666665

In [25]:
s.value_counts()

1.0    5
2.0    4
3.0    2
5.0    2
4.0    1
7.0    1
Name: count, dtype: int64

### index를 활용하여 멀티플한 값에 접근
- index를 리스트로 주면 된다

In [29]:
s[[5, 7, 8, 10]].value_counts()

1.0    2
2.0    1
3.0    1
Name: count, dtype: int64

## `head`, `tail` 함수
- `head`: 상위 n개 출력 (기본 5개)
- `tail`: 하위 n개 출력 (기본 5개)

In [30]:
s.head()

0    1.0
1    1.0
2    2.0
3    1.0
4    2.0
dtype: float64

In [33]:
s.head(10)

0    1.0
1    1.0
2    2.0
3    1.0
4    2.0
5    2.0
6    2.0
7    1.0
8    1.0
9    3.0
dtype: float64

In [31]:
s.tail()

11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

# Series 데이터 연산하기

## index를 기준으로 연산

### 산술연산
- Series의 경우에도 스칼라와의 연산은 각 원소별로 스칼라와의 연산이 적용
- Series와의 연산은 각 인덱스에 맞는 값끼리 연산이 적용
    - 이 때, 인덱스의 pair가 맞지 않으면, 결과는 NaN

In [34]:
s1 = pd.Series([1,2,3,4], ['a','b','c','d'])
s2 = pd.Series([6,3,2,1], ['d', 'c', 'b','a'])

s1

a    1
b    2
c    3
d    4
dtype: int64

In [35]:
s2

d    6
c    3
b    2
a    1
dtype: int64

In [36]:
s1 + s2 # 같은 인덱스 끼리 연산

a     2
b     4
c     6
d    10
dtype: int64

In [37]:
s1 ** 2

a     1
b     4
c     9
d    16
dtype: int64

In [38]:
s1 ** s2

a       1
b       4
c      27
d    4096
dtype: int64

### index pair가 맞지 않는 경우
- 해당 index에 대해선 NaN 값 생성

In [39]:
s1['k'] = 7
s2['e'] = 9

s1

a    1
b    2
c    3
d    4
k    7
dtype: int64

In [40]:
s2

d    6
c    3
b    2
a    1
e    9
dtype: int64

In [41]:
s1 + s2

a     2.0
b     4.0
c     6.0
d    10.0
e     NaN
k     NaN
dtype: float64

## Series 데이터 Boolean Selection으로 데이터 선택하기

### Boolean Selection
- boolean Series가 []와 함게 사용되면 True 값에 해당하는 값만 새로 반환되는 Series 객체에 포함됨
- 다중 조건의 경우, &(and), |(or)를 사용하여 연결 가능

In [42]:
s = pd.Series(np.arange(10), np.arange(10) + 1)
s

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int64

In [43]:
s > 5

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

In [44]:
s[s > 5]

7     6
8     7
9     8
10    9
dtype: int64

In [45]:
s[s % 2 == 0]

1    0
3    2
5    4
7    6
9    8
dtype: int64

In [46]:
s

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int64

In [47]:
s.index > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
s[s.index > 5]

6     5
7     6
8     7
9     8
10    9
dtype: int64

In [50]:
s[(s > 5) & (s < 8)] # Multiple 조건은 각 조건(condition)을 괄호로 묶어야 함

7    6
8    7
dtype: int64

In [51]:
# 문제

(s >= 7).sum() # 7이상의 값의 개수
(s[s>=7]).sum() # 7이상의 값의 합

24

# Series 데이터 변경 & 슬라이싱 하기

### Series 값 변경
- 추가 및 업데이트: 인덱스를 이용
- 삭제: drop 함수 이용 
    - 새로운 Series 반환(원본 변경 없음)

In [52]:
s = pd.Series(np.arange(100, 105), ['a', 'b', 'c', 'd', 'e'])
s

a    100
b    101
c    102
d    103
e    104
dtype: int64

In [53]:
s['a'] = 200
s

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [54]:
s['k'] = 300
s

a    200
b    101
c    102
d    103
e    104
k    300
dtype: int64

In [55]:
s.drop('k') # 복사본 반환

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [56]:
s

a    200
b    101
c    102
d    103
e    104
k    300
dtype: int64

In [57]:
s.drop('k', inplace = True) # 반환값이 없음 -> 복사본이 아니라 원본에 대해서 연산 적용

In [58]:
s

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [59]:
s[['a', 'b']] = [300, 900]
s

a    300
b    900
c    102
d    103
e    104
dtype: int64

### Slicing
- 리스트, ndarray와 동일하게 적용

In [60]:
s1 = pd.Series(np.arange(100, 105))
s1

0    100
1    101
2    102
3    103
4    104
dtype: int64

In [61]:
s1[1:3] # 정수 인덱스 접근 시 ndarray와 동일함

1    101
2    102
dtype: int64

In [62]:
s2 = pd.Series(np.arange(100, 105), ['a','b','c','d','e'])
s2

a    100
b    101
c    102
d    103
e    104
dtype: int64

In [63]:
s2[1:3] # 문자열 인덱스 시 인덱스 순서대로 접근, 마지막 인덱스는 포함 X

b    101
c    102
dtype: int64

In [64]:
s3 = pd.Series(np.arange(100, 105), ['a','c','b','d','e'])
s3

a    100
c    101
b    102
d    103
e    104
dtype: int64

In [65]:
s3['c':'d'] # 문자열 인덱스로 슬라이싱 시 마지막 인덱스를 포함

c    101
b    102
d    103
dtype: int64

# `Pandas.DataFrame`

## DataFrame
- Series가 1차원이라면, DataFrame은 2차원으로 확대된 버전
- Excel spreadsheet이라고 생각하면 이해하기 쉬움
- 2차원이기 때문에 인덱스가 row, column으로 구성됨
    - row는 각 개별 데이터를, column은 개별 속성을 의미
- Data Analysis, Machine Learning에서 data 변형을 위해 가장 많이 사용

In [69]:
import os
import pandas as pd
data_path = '../../kaggle_data/titanic'
file_name = 'train.csv'

train_data = pd.read_csv(os.path.join(data_path, file_name))

### `head`, `tail` 함수
- 데이터 전체가 아닌, 일부(처음부터, 혹은 마지막 부터)를 간단히 보기 위한 함수
- head: 상위 n개 데이터 (기본 5개)
- tail: 하위 n개 데이터 (기본 5개)

In [71]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [72]:
train_data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### dataframe 데이터 파악하기
- shape 속성(row, column)
- `describe` 함수 - 숫자형 데이터의 통계치 계산
- `info` 함수 - 데이터 타입, 각 아이템의 개수 등 출력

In [73]:
train_data.shape

(891, 12)

In [74]:
train_data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [75]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## DataFrame 구조 이해하기

### 인덱스 (index)
- index 속성 `dataframe.index`
- 각 아이템을 특정할 수 있는 고유의 값을 저장
        - 절대로 중복이 있을 수 없다
- 복잡한 데이터의 경우, 멀티 인덱스로 표현 가능

In [76]:
train_data.index

RangeIndex(start=0, stop=891, step=1)

In [77]:
train_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

## cf\) DataFrame 데이터 생성하기

### DataFrame 생성하기
- 일반적으로 분석을 위한 데이터는 다른 데이터 소스(database, 외부 파일)를 통해 dataframe을 생성
- 실습에서는 dummy 데이터를 생성하는 방법을 다룸

#### dictionary로 부터 생성하기
- dict의 key -> column

In [78]:
data = {'a': 100, 'b': 200, 'c' : 300}
df1 = pd.DataFrame(data, index=['x', 'y', 'z'])
df1

     a    b    c
x  100  200  300
y  100  200  300
z  100  200  300

In [79]:
data = {'a': [1,2,3], 'b': [4,5,6], 'c' : [10,11,12]}
df2 = pd.DataFrame(data, index = [0, 1, 2])
df2

   a  b   c
0  1  4  10
1  2  5  11
2  3  6  12

#### Series로 부터 생성하기
- 각 Series의 인덱스 -> column

In [81]:
a = pd.Series([100, 200, 300], ['a', 'b', 'd'])
b = pd.Series([101, 201, 301], ['a', 'b', 'k'])
c = pd.Series([110, 220, 310], ['a', 'b', 'c'])

pd.DataFrame([a,b,c], index = [100, 101, 102])

         a      b      d      k      c
100  100.0  200.0  300.0    NaN    NaN
101  101.0  201.0    NaN  301.0    NaN
102  110.0  220.0    NaN    NaN  310.0

## 샘플 CSV 데이터로 DataFrame 데이터 생성하기

### `pandas.read_csv()`함수와 파라미터
- sep: 각 데이터 값을 구별하기 위한 구분자(separator) 설정
    - sep의 기본값은 ','
- header: header를 무시할 경우 None
    - 자동으로 유추
- index_col: index로 사용할 column 설정
    - 명시하지 않으면 0 based 인덱스 생성
- usecols: 실제로 dataframe에 로딩할 columns만 설정

In [82]:
import os
import pandas as pd
data_path = '../../kaggle_data/titanic'
file_name = 'train.csv'

train_data = pd.read_csv(os.path.join(data_path, file_name))

In [83]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [84]:
train_data = pd.read_csv(os.path.join(data_path, file_name), index_col = 'PassengerId')
train_data

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## DataFrame 원하는 column만 선택하기

### column 선택하기
- 기본적으로 []는 column을 추출
- 컬럼 인덱스일 경우, 인덱스의 리스트 사용 가능
    - 리스트를 전달할 경우 결과는 DataFrame
    - 하나의 컬럼명을 전달할 경우 결과는 Series

#### 하나의 컬럼 선택하기

In [85]:
train_data[0] # Error

KeyError: 0

In [86]:
train_data['Survived'] # 결과는 Series

PassengerId
1      0
2      1
3      1
4      1
5      0
      ..
887    0
888    1
889    0
890    1
891    0
Name: Survived, Length: 891, dtype: int64

In [87]:
train_data[['Survived']] # 결과는 DataFrame

             Survived
PassengerId
1                   0
2                   1
3                   1
4                   1
5                   0
...               ...
887                 0
888                 1
889                 0
890                 1
891                 0

[891 rows x 1 columns]

#### 복수의 컬럼 선택하기

In [88]:
train_data[['Survived', 'Age', 'Name']] # 결과는 DataFrame

             Survived   Age                                               Name
PassengerId
1                   0  22.0                            Braund, Mr. Owen Harris
2                   1  38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
3                   1  26.0                             Heikkinen, Miss. Laina
4                   1  35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
5                   0  35.0                           Allen, Mr. William Henry
...               ...   ...                                                ...
887                 0  27.0                              Montvila, Rev. Juozas
888                 1  19.0                       Graham, Miss. Margaret Edith
889                 0   NaN           Johnston, Miss. Catherine Helen "Carrie"
890                 1  26.0                              Behr, Mr. Karl Howell
891                 0  32.0                                Dooley, Mr. Patrick

[891 rows x 3 columns]

## DataFrame 원하는 row(데이터)만 선택하기

### dataframe slicing
- dataframe의 경우 기본적으로 [] 연산자가 column 선택에 사용
- 하지만 slicing은 row 레벨로 지원

In [90]:
train_data = pd.read_csv(os.path.join(data_path, file_name))
train_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [91]:
# train_data[0] # Error
train_data[:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [92]:
train_data[7:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### row 선택하기
- Series의 경우 []로 row 선택이 가능하나, DataFrame의 경우는 기본적으로 column을 선택하도록 설계
- `.loc`, `.iloc`으로 row 선택 가능
    - `.loc`: 해당 데이터프레임의 인덱스 자체를 사용
    - `.iloc`: 0 based index로 사용
    - 두 함수는 `,`를 사용하여 column 선택도 가능
        - `loc`: 원 column_name으로 접근
        - `iloc`: column 또한 0 based index이기 때문에 정수 index로 접근

In [94]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [95]:
train_data.index = np.arange(100, 991)

In [96]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
101,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
102,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
103,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
104,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [97]:
train_data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
986,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
987,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
988,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
989,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
990,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [98]:
train_data.loc[986] # 결과는 Series

PassengerId                      887
Survived                           0
Pclass                             2
Name           Montvila, Rev. Juozas
Sex                             male
Age                             27.0
SibSp                              0
Parch                              0
Ticket                        211536
Fare                            13.0
Cabin                            NaN
Embarked                           S
Name: 986, dtype: object

In [99]:
train_data.loc[[986, 100, 110, 990]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
986,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
100,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
110,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.70,G6,S
990,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [101]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
101,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
102,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
103,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
104,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [100]:
train_data.iloc[0] # 결과는 Series

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 100, dtype: object

In [102]:
train_data.iloc[[0, 100, 200 ,2]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
200,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S
300,201,0,3,"Vande Walle, Mr. Nestor Cyriel",male,28.0,0,0,345770,9.5000,NaN,S
102,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [103]:
train_data.loc[[0, 100, 200 ,2]]

KeyError: '[0, 2] not in index'

### row, column 동시에 선택하기
- `loc`, `iloc` 속성을 이용할 때, 콤마를 이용하여 둘 다 명시 가능

In [104]:
train_data.loc[[986, 100, 110, 990], ['Survived', 'Name', 'Sex', 'Age']]

     Survived                             Name     Sex   Age
986         0            Montvila, Rev. Juozas    male  27.0
100         0          Braund, Mr. Owen Harris    male  22.0
110         1  Sandstrom, Miss. Marguerite Rut  female   4.0
990         0              Dooley, Mr. Patrick    male  32.0

In [105]:
train_data.iloc[[0, 100, 200 ,2], [1, 4, 5]]

     Survived     Sex   Age
100         0    male  22.0
200         0  female  28.0
300         0    male  28.0
102         1  female  26.0

## DataFrame Boolean Selection으로 데이터 선택하기

In [116]:
train_data = pd.read_csv(os.path.join(data_path, file_name))
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### boolean selection으로 row 선택하기
- numpy에서와 동일한 방식으로 해당 조건에 맞는 row만 선택

#### 실습\) 30대이면서 1등석에 탄 사람 선택하기

In [106]:
pass_class = train_data['Pclass'] == 1
pass_age = (train_data['Age'] >= 30 ) & (train_data['Age'] <40)
train_data[pass_class & pass_age]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
101,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
103,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
161,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN
237,138,0,1,"Futrelle, Mr. Jacques Heath",male,37.0,1,0,113803,53.1000,C123,S
315,216,1,1,"Newell, Miss. Madeleine",female,31.0,1,0,35273,113.2750,D36,C
318,219,1,1,"Bazzani, Miss. Albina",female,32.0,0,0,11813,76.2917,D15,C
324,225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38.0,1,0,19943,90.0000,C93,S
330,231,1,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",female,35.0,1,0,36973,83.4750,C83,S
348,249,1,1,"Beckwith, Mr. Richard Leonard",male,37.0,1,1,11751,52.5542,D35,S
357,258,1,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.5000,B77,S
358,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
369,270,1,1,"Bissette, Miss. Amelia",female,35.0,0,0,PC 17760,135.6333,C99,S
373,274,0,1,"Natsch, Mr. Charles H",male,37.0,0,1,PC 17596,29.7000,C118,C
409,310,1,1,"Francatelli, Miss. Laura Mabel",female,30.0,0,0,PC 17485,56.9292,E36,C
418,319,1,1,"Wick, Miss. Mary Natalie",female,31.0,0,2,36928,164.8667,C7,S
425,326,1,1,"Young, Miss. Marie Grice",female,36.0,0,0,PC 17760,135.6333,C32,C
432,333,0,1,"Graham, Mr. George Edward",male,38.0,0,1,PC 17582,153.4625,C91,S
483,384,1,1,"Holverson, Mrs. Alexander Oskar (Mary Aline To...",female,35.0,1,0,113789,52.0000,NaN,S
490,391,1,1,"Carter, Mr. William Ernest",male,36.0,1,2,113760,120.0000,B96 B98,S
512,413,1,1,"Minahan, Miss. Daisy E",female,33.0,1,0,19928,90.0000,C78,Q
547,448,1,1,"Seward, Mr. Frederic Kimber",male,34.0,0,0,113794,26.5500,NaN,S
552,453,0,1,"Foreman, Mr. Benjamin Laventall",male,30.0,0,0,113051,27.7500,C111,C
586,487,1,1,"Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)",female,35.0,1,0,19943,90.0000,C93,S
612,513,1,1,"McGough, Mr. James Robert",male,36.0,0,0,PC 17473,26.2875,E25,S
620,521,1,1,"Perreault, Miss. Anne",female,30.0,0,0,12749,93.5000,B73,S
637,538,1,1,"LeRoy, Miss. Bertha",female,30.0,0,0,PC 17761,106.4250,NaN,C
640,541,1,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.0000,B22,S
658,559,1,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.6500,E67,S
672,573,1,1,"Flynn, Mr. John Irwin (""Irving"")",male,36.0,0,0,PC 17474,26.3875,E25,S
677,578,1,1,"Silvey, Mrs. William Baird (Alice Munger)",female,39.0,1,0,13507,55.9000,E44,S
681,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.0,1,1,17421,110.8833,C68,C
683,584,0,1,"Ross, Mr. John Hugo",male,36.0,0,0,13049,40.1250,A10,C
704,605,1,1,"Homer, Mr. Harry (""Mr E Haven"")",male,35.0,0,0,111426,26.5500,NaN,C
732,633,1,1,"Stahelin-Maeglin, Dr. Max",male,32.0,0,0,13214,30.5000,B50,C
771,672,0,1,"Davidson, Mr. Thornton",male,31.0,1,0,F.C. 12750,52.0000,B71,S
779,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
790,691,1,1,"Dick, Mr. Albert Adrian",male,31.0,1,0,17474,57.0000,B20,S
801,702,1,1,"Silverthorne, Mr. Spencer Victor",male,35.0,0,0,PC 17475,26.2875,E24,S
816,717,1,1,"Endres, Miss. Caroline Louise",female,38.0,0,0,PC 17757,227.5250,C45,C
837,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
841,742,0,1,"Cavendish, Mr. Tyrell William",male,36.0,1,0,19877,78.8500,C46,S
859,760,1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.5000,B77,S
863,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.0,1,2,113760,120.0000,B96 B98,S
906,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S
909,810,1,1,"Chambers, Mrs. Norman Campbell (Bertha Griggs)",female,33.0,1,0,113806,53.1000,E8,S
922,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,NaN,S
935,836,1,1,"Compton, Miss. Sara Rebecca",female,39.0,1,1,PC 17756,83.1583,E49,C
942,843,1,1,"Serepeca, Miss. Augusta",female,30.0,0,0,113798,31.0000,NaN,C
967,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
972,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S

## DataFrame에 column 추가 & 삭제하기

### 새 column 추가하기
- [] 사용하여 추가하기
- insert 함수 사용하여 원하는 위치에 추가하기

In [107]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
101,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
102,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
103,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
104,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [109]:
train_data['Age_Double'] = train_data['Age'] * 2 # 마지막에 column 추가
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Double
100,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,44.0
101,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,76.0
102,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,52.0
103,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,70.0
104,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,70.0

In [110]:
train_data['Age_Tripple'] = train_data['Age'] + train_data['Age_Double'] # 기존 column들을 더해서 새로운 column 생성
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Double,Age_Tripple
100,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,44.0,66.0
101,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,76.0,114.0
102,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,52.0,78.0
103,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,70.0,105.0
104,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,70.0,105.0

In [111]:
train_data.insert(3, 'Fare10', train_data['Fare'] / 10) # insert 함수를 사용하여 원하는 location에 column 삽입
train_data.head()

,PassengerId,Survived,Pclass,Fare10,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Double,Age_Tripple
100,1,0,3,0.72500,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,44.0,66.0
101,2,1,1,7.12833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,76.0,114.0
102,3,1,3,0.79250,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,52.0,78.0
103,4,1,1,5.31000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,70.0,105.0
104,5,0,3,0.80500,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,70.0,105.0

### column 삭제하기
- drop 함수 사용하여 삭제
    - 기본 옵션 `inplace = False`: 해당 컬럼 삭제한 복사본 반환
    - `inplace = True`: 원본에 해당 컬럼 삭제
- 리스트를 사용하여 멀티플 column 삭제 가능

In [112]:
train_data.drop('Age_Tripple', axis = 1) # inplace = False 기 때문에 복사본 리턴

,PassengerId,Survived,Pclass,Fare10,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Double
100,1,0,3,0.72500,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,44.0
101,2,1,1,7.12833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,76.0
102,3,1,3,0.79250,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,52.0
103,4,1,1,5.31000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,70.0
104,5,0,3,0.80500,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,887,0,2,1.30000,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,54.0
987,888,1,1,3.00000,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,38.0
988,889,0,3,2.34500,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
989,890,1,1,3.00000,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,52.0
990,891,0,3,0.77500,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,64.0

In [113]:
train_data.drop('Age_Tripple', axis = 1, inplace = True)
train_data.head()

,PassengerId,Survived,Pclass,Fare10,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Double
100,1,0,3,0.72500,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,44.0
101,2,1,1,7.12833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,76.0
102,3,1,3,0.79250,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,52.0
103,4,1,1,5.31000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,70.0
104,5,0,3,0.80500,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,70.0

In [115]:
train_data.drop(['Age_Double', 'Fare10'], axis = 1, inplace = True)
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
101,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
102,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
103,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
104,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## DataFrame column간 상관관계 계산하기

### 변수(column) 사이의 상관계수(correlation)
- `corr` 함수를 통해 상관계수 연산 (-1, 1 사이의 결과)
    - 연속형(숫자형) 데이터에 대해서만 연산
    - 상관관계는 인과관계를 의미하지 않음

In [119]:
train_data = pd.read_csv(os.path.join(data_path, file_name))
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [120]:
train_data.corr('pearson', numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

## DataFrame NaN 데이터 처리

In [121]:
train_data = pd.read_csv(os.path.join(data_path, file_name))
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### NaN 값 확인
- `info` 함수를 통하여 개수 확인
- `isna` 함수를 통해 boolean 타입으로 확인

In [122]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [123]:
train_data.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [124]:
train_data['Age'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

### NaN 처리 방법
- 데이터에서 삭제
    - `dropna` 함수
        - 옵션 명시 없을 시 (NaN이 하나라도 존재하는 row는 모두 drop) -> 데이터 손실의 위험
        - `subset` 파라미터 -> 해당 column의 값이 NaN이면 drop
- 다른 값으로 치환
    - `fillna` 함수
- NaN 데이터 삭제하기

In [125]:
train_data.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [127]:
train_data.dropna(subset=['Age', 'Cabin'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [128]:
train_data.dropna(axis = 1) # axis = 1 -> NaN이 하나라도 있는 column drop

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500

#### NaN 값 대체하기
- 평균으로 대체하기
- 선형보간법 등

In [129]:
train_data['Age'].fillna(train_data['Age'].mean()) # -> 복사본 반환
#train_data['Age'].fillna(train_data['Age'].mean(), inplace=True) # -> 원본 값 변경

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [130]:
# 생존자 나이 평균
mean1 = train_data[train_data['Survived'] == 1]['Age'].mean()

# 사망자 나이 평균
mean0 = train_data[train_data['Survived'] == 0]['Age'].mean() 

print(mean1, mean0)

28.343689655172415 30.62617924528302

In [131]:
train_data.loc[train_data['Survived'] == 1, 'Age'] = train_data[train_data['Survived'] == 1]['Age'].fillna(mean1)
train_data.loc[train_data['Survived'] == 0, 'Age'] = train_data[train_data['Survived'] == 0]['Age'].fillna(mean0)

In [132]:
train_data[train_data['Survived'] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

## 숫자 데이터와 범주형 데이터의 이해

In [133]:
train_data = pd.read_csv(os.path.join(data_path, file_name))
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### info 함수로 각 변수의 데이터 타입 확인
- 타입 변경은 `astype` 함수를 사용

In [134]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### 숫자형(Numerical Type) 데이터
- 연속성을 띄는 숫자로 이루어진 데이터(크고 작음이 의미가 있음)
    - 예시: Age, Fare 등

### 범주형(Categorical Type) 데이터
- 연속적이지 않은 값(대부분의 경우 숫자를 제외한 나머지 값)을 갖는 데이터를 의미
    - 예시: Name, Sex, Ticket, Cabin, Embarked 등
- 또한, 숫자형 타입이라 할 지라도 개념적으로 범주형으로 처리해야 할 경우가 있음
    - 예시: Pclass

## 숫자 데이터의 범주형 데이터화

#### Pclass 변수 변환하기
- `astype` 사용하여 간단히 타입만 변환

In [135]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [136]:
train_data['Pclass'] = train_data['Pclass'].astype('str')

#### Age 변수 변환하기
- 변환 로직을 함수로 만든 후, apply 함수로 적용
- numpy와 pandas에서는 for문 사용을 최소화 해야함

In [137]:
import math

In [139]:
def age_categorize(age):
    if math.isnan(age):
        return -1
    return math.floor(age / 10) * 10

In [140]:
train_data['Age'].apply(age_categorize)

0      20
1      30
2      20
3      30
4      30
       ..
886    20
887    10
888    -1
889    20
890    30
Name: Age, Length: 891, dtype: int64

## 범주형 데이터 전처리 하기(one-hot encoding)

### One-Hot Encoding
- 범주형 데이터는 분석단게에서 계산이 어렵기 때문에 숫자형으로 변경이 필요함
- 범주형 데이터의 각 범주(category)를 column 레벨로 변경
- 해당 범주에 해당하면 1, 아니면 0으로 채우는 인코딩 기법
- `pandas.get_dummies()` 함수 사용
    - `drop_first`: 첫 번째 카테고리 값은 사용하지 않음

In [ ]:
pd.get_dummies(train_data, columns=['Pclass', 'Sex', 'Embarked'], drop_first=False)

,PassengerId,Survived,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,False,False,True,False,True,False,False,True
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,True,False,False,True,False,True,False,False
2,3,1,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,False,False,True,True,False,False,False,True
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,True,False,False,True,False,False,False,True
4,5,0,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,False,False,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,False,True,False,False,True,False,False,True
887,888,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,True,False,False,True,False,False,False,True
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,False,False,True,True,False,False,False,True
889,890,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,True,False,False,False,True,True,False,False
890,891,0,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,False,False,True,False,True,False,True,False

In [143]:
pd.get_dummies(train_data, columns=['Pclass', 'Sex', 'Embarked'], drop_first=True)

,PassengerId,Survived,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Pclass_2,Pclass_3,Sex_male,Embarked_Q,Embarked_S
0,1,0,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,False,True,True,False,True
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,False,False,False,False,False
2,3,1,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,False,True,False,False,True
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,False,False,False,False,True
4,5,0,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,True,False,True,False,True
887,888,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,False,False,False,False,True
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,False,True,False,False,True
889,890,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,False,False,True,False,False
890,891,0,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,False,True,True,True,False

# DataFrame의 그룹핑

## DataFrame group by 이해하기

In [144]:
df = pd.read_csv(os.path.join(data_path, file_name))
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### GroupBy gruops 속성
- 각 그룹과 그룹에 속한 index를 dict 형태로 표현

In [145]:
class_group = df.groupby('Pclass')
class_group

In [146]:
class_group.groups

{1: [1, 3, 6, 11, 23, 27, 30, 31, 34, 35, 52, 54, 55, 61, 62, 64, 83, 88, 92, 96, 97, 102, 110, 118, 124, 136, 137, 139, 151, 155, 166, 168, 170, 174, 177, 185, 187, 194, 195, 209, 215, 218, 224, 230, 245, 248, 252, 256, 257, 258, 262, 263, 268, 269, 270, 273, 275, 284, 290, 291, 295, 297, 298, 299, 305, 306, 307, 309, 310, 311, 318, 319, 325, 329, 331, 332, 334, 336, 337, 339, 341, 351, 356, 366, 369, 370, 373, 375, 377, 380, 383, 390, 393, 412, 430, 434, 435, 438, 445, 447, ...], 2: [9, 15, 17, 20, 21, 33, 41, 43, 53, 56, 58, 66, 70, 72, 78, 84, 98, 99, 117, 120, 122, 123, 133, 134, 135, 144, 145, 148, 149, 150, 161, 178, 181, 183, 190, 191, 193, 199, 211, 213, 217, 219, 221, 226, 228, 232, 234, 236, 237, 238, 239, 242, 247, 249, 259, 265, 272, 277, 288, 292, 303, 308, 312, 314, 316, 317, 322, 323, 327, 340, 342, 343, 344, 345, 346, 357, 361, 385, 387, 389, 397, 398, 399, 405, 407, 413, 416, 417, 418, 426, 427, 432, 437, 439, 440, 443, 446, 450, 458, 463, ...], 3: [0, 2, 4, 5, 7, 8, 10, 12, 13, 14, 16, 18, 19, 22, 24, 25, 26, 28, 29, 32, 36, 37, 38, 39, 40, 42, 44, 45, 46, 47, 48, 49, 50, 51, 57, 59, 60, 63, 65, 67, 68, 69, 71, 73, 74, 75, 76, 77, 79, 80, 81, 82, 85, 86, 87, 89, 90, 91, 93, 94, 95, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 119, 121, 125, 126, 127, 128, 129, 130, 131, 132, 138, 140, 141, 142, 143, 146, 147, 152, 153, 154, 156, 157, 158, 159, ...]}

In [147]:
gender_group = df.groupby('Sex')
gender_group.groups

{'female': [1, 2, 3, 8, 9, 10, 11, 14, 15, 18, 19, 22, 24, 25, 28, 31, 32, 38, 39, 40, 41, 43, 44, 47, 49, 52, 53, 56, 58, 61, 66, 68, 71, 79, 82, 84, 85, 88, 98, 100, 106, 109, 111, 113, 114, 119, 123, 128, 132, 133, 136, 140, 141, 142, 147, 151, 156, 161, 166, 167, 172, 177, 180, 184, 186, 190, 192, 194, 195, 198, 199, 205, 208, 211, 215, 216, 218, 229, 230, 233, 235, 237, 240, 241, 246, 247, 251, 254, 255, 256, 257, 258, 259, 264, 268, 269, 272, 274, 275, 276, ...], 'male': [0, 4, 5, 6, 7, 12, 13, 16, 17, 20, 21, 23, 26, 27, 29, 30, 33, 34, 35, 36, 37, 42, 45, 46, 48, 50, 51, 54, 55, 57, 59, 60, 62, 63, 64, 65, 67, 69, 70, 72, 73, 74, 75, 76, 77, 78, 80, 81, 83, 86, 87, 89, 90, 91, 92, 93, 94, 95, 96, 97, 99, 101, 102, 103, 104, 105, 107, 108, 110, 112, 115, 116, 117, 118, 120, 121, 122, 124, 125, 126, 127, 129, 130, 131, 134, 135, 137, 138, 139, 143, 144, 145, 146, 148, 149, 150, 152, 153, 154, 155, ...]}

#### groupping 함수
- 그룹 데이터에 적용 가능한 통계 함수(NaN은 제외하여 연산)
- count - 데이터 개수
- sum - 데이터의 합
- mean, std, var - 평균, 표준편차, 분산
- min, max - 최소, 최대

In [148]:
class_group.count()

# Age, Cabin 등은 NaN 때문에 빠지는 값들이 있다

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,216,216,216,216,186,216,216,216,216,176,214
2,184,184,184,184,173,184,184,184,184,16,184
3,491,491,491,491,355,491,491,491,491,12,491

In [149]:
class_group.sum()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,99705,136,"Cumings, Mrs. John Bradley (Florence Briggs Th...",femalefemalemalefemalemalemalemalefemalemalema...,7111.42,90,77,PC 175991138031746311378311378819950PC 17601PC...,18177.4125,C85C123E46C103A6C23 C25 C27B78D33B30C52B28C83C...,CSSSSSCCCSCCSSCSSSCCSSCSSSCSCSSSCCSSCCCCCSSQSS...
2,82056,87,"Nasser, Mrs. Nicholas (Adele Achem)Hewlett, Mr...",femalefemalemalemalemalemalefemalefemalefemale...,5168.83,74,70,237736248706244373239865248698C.A. 2457911668S...,3801.8417,D56F33E101F2F4F2DE101DF2F33DF33F4E101E77,CSSSSSSCSSSSSSSSSSSSCSSSCSSSSSSSCSSSSSSSSSSSSS...
3,215625,119,"Braund, Mr. Owen HarrisHeikkinen, Miss. LainaA...",malefemalemalemalemalefemalefemalemalemalefema...,8924.92,302,193,A/5 21171STON/O2. 3101282373450330877349909347...,6714.6951,G6F G73F E69G6G6G6E10F G63F G73E121F38E121,SSSQSSSSSSQSCQSSCQSQCSSCSCQSQQCSSSCSCSCSSSSCSS...

In [152]:
class_group.mean(numeric_only=True)['Survived']

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [154]:
class_group.max(numeric_only=True)

        PassengerId  Survived   Age  SibSp  Parch      Fare
Pclass
1               890         1  80.0      3      4  512.3292
2               887         1  70.0      3      3   73.5000
3               891         1  74.0      8      6   69.5500

In [155]:
df.groupby('Sex').mean(numeric_only=True)['Survived']

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

#### 복수 columns로 groupping 하기
- groupby에 column 리스트를 전달
- 통계함수를 적용한 결과는 multi index를 가지는 dataframe
---
- 예제\) 클래스와 성별에 따른 생존률 구해보기

In [157]:
df.groupby(['Pclass', 'Sex']).mean(numeric_only=True)

               PassengerId  Survived        Age     SibSp     Parch  \
Pclass Sex
1      female   469.212766  0.968085  34.611765  0.553191  0.457447
       male     455.729508  0.368852  41.281386  0.311475  0.278689
2      female   443.105263  0.921053  28.722973  0.486842  0.605263
       male     447.962963  0.157407  30.740707  0.342593  0.222222
3      female   399.729167  0.500000  21.750000  0.895833  0.798611
       male     455.515850  0.135447  26.507589  0.498559  0.224784

                     Fare
Pclass Sex
1      female  106.125798
       male     67.226127
2      female   21.970121
       male     19.741782
3      female   16.118810
       male     12.661633

In [158]:
df.groupby(['Pclass', 'Sex']).mean(numeric_only=True).index

MultiIndex([(1, 'female'),
            (1,   'male'),
            (2, 'female'),
            (2,   'male'),
            (3, 'female'),
            (3,   'male')],
           names=['Pclass', 'Sex'])

#### index를 이용한 group by
- index가 있는 경우, groupby 함수에 level 사용 가능
    - level은 index의 depth를 의미하며, 가장 왼쪽부터 0부터 증가
- `set_index` 함수
    - column 데이터를 index 레벨로 변경
- `reset_index` 함수
    - 인덱스 초기화

In [159]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [160]:
df.set_index(['Pclass', 'Sex']).reset_index()

,Pclass,Sex,PassengerId,Survived,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,male,1,0,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,female,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C
2,3,female,3,1,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,female,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S
4,3,male,5,0,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,male,887,0,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,S
887,1,female,888,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S
888,3,female,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,male,890,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C
890,3,male,891,0,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,Q

In [161]:
df.set_index('Age').groupby(level=0).mean(numeric_only=True)

       PassengerId  Survived  Pclass  SibSp  Parch      Fare
Age
0.42         804.0       1.0     3.0    0.0    1.0    8.5167
0.67         756.0       1.0     2.0    1.0    1.0   14.5000
0.75         557.5       1.0     3.0    2.0    1.0   19.2583
0.83         455.5       1.0     2.0    0.5    1.5   23.8750
0.92         306.0       1.0     1.0    1.0    2.0  151.5500
...            ...       ...     ...    ...    ...       ...
70.00        709.5       0.0     1.5    0.5    0.5   40.7500
70.50        117.0       0.0     3.0    0.0    0.0    7.7500
71.00        295.5       0.0     1.0    0.0    0.0   42.0792
74.00        852.0       0.0     3.0    0.0    0.0    7.7750
80.00        631.0       1.0     1.0    0.0    0.0   30.0000

[88 rows x 6 columns]

#### 나이대별로 생존율 구하기

In [163]:
import math

def age_categorize(age):
    if math.isnan(age):
        return -1
    return math.floor(age / 10) * 10

In [164]:
df.set_index('Age').groupby(age_categorize).mean(numeric_only=True)['Survived']

Age
-1     0.293785
 0     0.612903
 10    0.401961
 20    0.350000
 30    0.437126
 40    0.382022
 50    0.416667
 60    0.315789
 70    0.000000
 80    1.000000
Name: Survived, dtype: float64

#### Multi Index를 이용한 groupping

In [167]:
df.set_index(['Pclass', 'Age']).groupby(level=[0, 1]).mean(numeric_only=True)

              PassengerId  Survived  SibSp  Parch      Fare
Pclass Age
1      0.92         306.0       1.0    1.0    2.0  151.5500
       2.00         298.0       0.0    1.0    2.0  151.5500
       4.00         446.0       1.0    0.0    2.0   81.8583
       11.00        803.0       1.0    1.0    2.0  120.0000
       14.00        436.0       1.0    1.0    2.0  120.0000
...                   ...       ...    ...    ...       ...
3      61.00        327.0       0.0    0.0    0.0    6.2375
       63.00        484.0       1.0    0.0    0.0    9.5875
       65.00        281.0       0.0    0.0    0.0    7.7500
       70.50        117.0       0.0    0.0    0.0    7.7500
       74.00        852.0       0.0    0.0    0.0    7.7750

[182 rows x 5 columns]

In [168]:
df.set_index(['Pclass', 'Age']).groupby(level=[1, 0]).mean(numeric_only=True)

              PassengerId  Survived  SibSp  Parch      Fare
Age   Pclass
0.42  3             804.0       1.0    0.0    1.0    8.5167
0.67  2             756.0       1.0    1.0    1.0   14.5000
0.75  3             557.5       1.0    2.0    1.0   19.2583
0.83  2             455.5       1.0    0.5    1.5   23.8750
0.92  1             306.0       1.0    1.0    2.0  151.5500
...                   ...       ...    ...    ...       ...
70.00 2             673.0       0.0    0.0    0.0   10.5000
70.50 3             117.0       0.0    0.0    0.0    7.7500
71.00 1             295.5       0.0    0.0    0.0   42.0792
74.00 3             852.0       0.0    0.0    0.0    7.7750
80.00 1             631.0       1.0    0.0    0.0   30.0000

[182 rows x 5 columns]

#### Aggregate함수(집계함수) 사용하기
- groupby 결과에 집계함수를 적용하여 그룹별 데이터 확인 가능

In [170]:
df.set_index(['Pclass', 'Age']).groupby(level=[0, 1]).aggregate([np.mean, np.sum, np.max])

/var/folders/ws/yk5_j0490vnb543l1m2l7mtc0000gn/T/ipykernel_34764/1738585118.py:1: FutureWarning: The provided callable <function mean at 0x105705c10> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.set_index(['Pclass', 'Age']).groupby(level=[0, 1]).aggregate([np.mean, np.sum, np.max])
/var/folders/ws/yk5_j0490vnb543l1m2l7mtc0000gn/T/ipykernel_34764/1738585118.py:1: FutureWarning: The provided callable <function sum at 0x105702790> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.set_index(['Pclass', 'Age']).groupby(level=[0, 1]).aggregate([np.mean, np.sum, np.max])
/var/folders/ws/yk5_j0490vnb543l1m2l7mtc0000gn/T/ipykernel_34764/1738585118.py:1: FutureWarning: The provided callable <function amax at 0x105705040> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.set_index(['Pclass', 'Age']).groupby(level=[0, 1]).aggregate([np.mean, np.sum, np.max])

TypeError: agg function failed [how->mean,dtype->object]

## `transform` 함수의 이해 및 활용하기

### `transform` 함수
- groupby 후 transform 함수를 사용하면 원래의 index를 유지한 상태로 통계함수를 적용
- 전체 데이터의 집계가 아닌 각 그룹에서의 집계를 계산
- 새로 생성된 데이터를 원본 dataframe과 합치기 쉬움

In [ ]:
df.groupby('Pclass').mean(numeric_only=True)

        PassengerId  Survived        Age     SibSp     Parch       Fare
Pclass
1        461.597222  0.629630  38.233441  0.416667  0.356481  84.154687
2        445.956522  0.472826  29.877630  0.402174  0.380435  20.662183
3        439.154786  0.242363  25.140620  0.615071  0.393075  13.675550

In [174]:
df.groupby('Pclass').transform(np.mean,numeric_only=True)

/var/folders/ws/yk5_j0490vnb543l1m2l7mtc0000gn/T/ipykernel_34764/60995919.py:1: FutureWarning: The provided callable <function mean at 0x105705c10> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('Pclass').transform(np.mean,numeric_only=True)

     PassengerId  Survived        Age     SibSp     Parch       Fare
0     439.154786  0.242363  25.140620  0.615071  0.393075  13.675550
1     461.597222  0.629630  38.233441  0.416667  0.356481  84.154687
2     439.154786  0.242363  25.140620  0.615071  0.393075  13.675550
3     461.597222  0.629630  38.233441  0.416667  0.356481  84.154687
4     439.154786  0.242363  25.140620  0.615071  0.393075  13.675550
..           ...       ...        ...       ...       ...        ...
886   445.956522  0.472826  29.877630  0.402174  0.380435  20.662183
887   461.597222  0.629630  38.233441  0.416667  0.356481  84.154687
888   439.154786  0.242363  25.140620  0.615071  0.393075  13.675550
889   461.597222  0.629630  38.233441  0.416667  0.356481  84.154687
890   439.154786  0.242363  25.140620  0.615071  0.393075  13.675550

[891 rows x 6 columns]

In [176]:
df['Age2'] = df.groupby('Pclass').transform(np.mean,numeric_only=True)['Age']
df

/var/folders/ws/yk5_j0490vnb543l1m2l7mtc0000gn/T/ipykernel_34764/4180614136.py:1: FutureWarning: The provided callable <function mean at 0x105705c10> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df['Age2'] = df.groupby('Pclass').transform(np.mean,numeric_only=True)['Age']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age2
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,25.140620
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.233441
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,25.140620
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,38.233441
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,25.140620
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,29.877630
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,38.233441
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,25.140620
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,38.233441
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,25.140620

In [178]:
df.groupby(['Pclass', 'Sex']).mean(numeric_only=True)

               PassengerId  Survived        Age     SibSp     Parch  \
Pclass Sex
1      female   469.212766  0.968085  34.611765  0.553191  0.457447
       male     455.729508  0.368852  41.281386  0.311475  0.278689
2      female   443.105263  0.921053  28.722973  0.486842  0.605263
       male     447.962963  0.157407  30.740707  0.342593  0.222222
3      female   399.729167  0.500000  21.750000  0.895833  0.798611
       male     455.515850  0.135447  26.507589  0.498559  0.224784

                     Fare       Age2
Pclass Sex
1      female  106.125798  38.233441
       male     67.226127  38.233441
2      female   21.970121  29.877630
       male     19.741782  29.877630
3      female   16.118810  25.140620
       male     12.661633  25.140620

In [180]:
df['Age3'] = df.groupby(['Pclass', 'Sex']).transform(np.mean,numeric_only=True)['Age']
df

/var/folders/ws/yk5_j0490vnb543l1m2l7mtc0000gn/T/ipykernel_34764/4274099223.py:1: FutureWarning: The provided callable <function mean at 0x105705c10> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df['Age3'] = df.groupby(['Pclass', 'Sex']).transform(np.mean,numeric_only=True)['Age']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age2,Age3
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,25.140620,26.507589
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.233441,34.611765
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,25.140620,21.750000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,38.233441,34.611765
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,25.140620,26.507589
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,29.877630,30.740707
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,38.233441,34.611765
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,25.140620,21.750000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,38.233441,41.281386
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,25.140620,26.507589

## pivot, pivot_table 함수의 이해 및 활용하기

In [189]:
df = pd.DataFrame({
    '지역': ['서울', '서울', '서울', '경기', '경기', '부산', '서울', '서울', '부산', '경기', '경기', '경기'],
    '요일': ['월요일', '월요일', '수요일', '월요일', '화요일', '월요일', '목요일', '금요일', '화요일', '수요일', '목요일', '금요일'],
    '강수량': [100, 80, 1000, 200, 200, 100, 50, 100, 200, 100, 50, 100],
    '강수확률': [80, 70, 90, 10, 20, 30, 50, 90, 20, 80, 50, 10]
                })

df

    지역   요일   강수량  강수확률
0   서울  월요일   100    80
1   서울  월요일    80    70
2   서울  수요일  1000    90
3   경기  월요일   200    10
4   경기  화요일   200    20
5   부산  월요일   100    30
6   서울  목요일    50    50
7   서울  금요일   100    90
8   부산  화요일   200    20
9   경기  수요일   100    80
10  경기  목요일    50    50
11  경기  금요일   100    10

### pivot
- dataframe의 형태를 변경
- 인덱스, 컬럼, 데이터로 사용할 컬럼을 명시

In [188]:
df.pivot(index = '지역', columns='요일')

ValueError: Index contains duplicate entries, cannot reshape

### pivot_table
- 기능적으로 pivot과 동일
- pivot과 차이점
    - 중복되는 모호한 값이 있을 경우, aggregation 함수 사용하여 값을 채움

In [190]:
pd.pivot_table(df, index = '요일', columns = '지역', aggfunc = np.mean)

/var/folders/ws/yk5_j0490vnb543l1m2l7mtc0000gn/T/ipykernel_34764/3976538692.py:1: FutureWarning: The provided callable <function mean at 0x105705c10> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df, index = '요일', columns = '지역', aggfunc = np.mean)

       강수량                 강수확률
지역      경기     부산      서울    경기    부산    서울
요일
금요일  100.0    NaN   100.0  10.0   NaN  90.0
목요일   50.0    NaN    50.0  50.0   NaN  50.0
수요일  100.0    NaN  1000.0  80.0   NaN  90.0
월요일  200.0  100.0    90.0  10.0  30.0  75.0
화요일  200.0  200.0     NaN  20.0  20.0   NaN

## stack, unstack 함수의 이해 및 활용

In [191]:
df = pd.DataFrame({
    '지역': ['서울', '서울', '서울', '경기', '경기', '부산', '서울', '서울', '부산', '경기', '경기', '경기'],
    '요일': ['월요일', '화요일', '수요일', '월요일', '화요일', '월요일', '목요일', '금요일', '화요일', '수요일', '목요일', '금요일'],
    '강수량': [100, 80, 1000, 200, 200, 100, 50, 100, 200, 100, 50, 100],
    '강수확률': [80, 70, 90, 10, 20, 30, 50, 90, 20, 80, 50, 10]
                })

df

    지역   요일   강수량  강수확률
0   서울  월요일   100    80
1   서울  화요일    80    70
2   서울  수요일  1000    90
3   경기  월요일   200    10
4   경기  화요일   200    20
5   부산  월요일   100    30
6   서울  목요일    50    50
7   서울  금요일   100    90
8   부산  화요일   200    20
9   경기  수요일   100    80
10  경기  목요일    50    50
11  경기  금요일   100    10

### stack \& unstack
- stack: 컬럼 레벨에서 인덱스 레벨로 dataframe 변경
    - 즉, 데이터를 쌓아 올리는 개념으로 이해하면 쉬움
- unstack: 인덱스 레벨에서 컬럼 레벨로 dataframe 변경
    - stack의 반대 operation
- 두 함수는 역의 관계에 있음

In [192]:
new_df = df.set_index(['지역','요일'])
new_df

         강수량  강수확률
지역 요일
서울 월요일   100    80
   화요일    80    70
   수요일  1000    90
경기 월요일   200    10
   화요일   200    20
부산 월요일   100    30
서울 목요일    50    50
   금요일   100    90
부산 화요일   200    20
경기 수요일   100    80
   목요일    50    50
   금요일   100    10

In [193]:
new_df.index

MultiIndex([('서울', '월요일'),
            ('서울', '화요일'),
            ('서울', '수요일'),
            ('경기', '월요일'),
            ('경기', '화요일'),
            ('부산', '월요일'),
            ('서울', '목요일'),
            ('서울', '금요일'),
            ('부산', '화요일'),
            ('경기', '수요일'),
            ('경기', '목요일'),
            ('경기', '금요일')],
           names=['지역', '요일'])

In [194]:
new_df.unstack(0)

       강수량                 강수확률
지역      경기     부산      서울    경기    부산    서울
요일
금요일  100.0    NaN   100.0  10.0   NaN  90.0
목요일   50.0    NaN    50.0  50.0   NaN  50.0
수요일  100.0    NaN  1000.0  80.0   NaN  90.0
월요일  200.0  100.0   100.0  10.0  30.0  80.0
화요일  200.0  200.0    80.0  20.0  20.0  70.0

In [195]:
new_df.unstack(1)

      강수량                              강수확률
요일    금요일   목요일     수요일    월요일    화요일   금요일   목요일   수요일   월요일   화요일
지역
경기  100.0  50.0   100.0  200.0  200.0  10.0  50.0  80.0  10.0  20.0
부산    NaN   NaN     NaN  100.0  200.0   NaN   NaN   NaN  30.0  20.0
서울  100.0  50.0  1000.0  100.0   80.0  90.0  50.0  90.0  80.0  70.0

In [197]:
new_df.unstack(0).stack(0)

/var/folders/ws/yk5_j0490vnb543l1m2l7mtc0000gn/T/ipykernel_34764/3150064354.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  new_df.unstack(0).stack(0)

지역           경기     부산      서울
요일
금요일 강수량   100.0    NaN   100.0
    강수확률   10.0    NaN    90.0
목요일 강수량    50.0    NaN    50.0
    강수확률   50.0    NaN    50.0
수요일 강수량   100.0    NaN  1000.0
    강수확률   80.0    NaN    90.0
월요일 강수량   200.0  100.0   100.0
    강수확률   10.0   30.0    80.0
화요일 강수량   200.0  200.0    80.0
    강수확률   20.0   20.0    70.0

In [198]:
new_df.unstack(0).stack(1)

/var/folders/ws/yk5_j0490vnb543l1m2l7mtc0000gn/T/ipykernel_34764/1778177021.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  new_df.unstack(0).stack(1)

           강수량  강수확률
요일  지역
금요일 경기   100.0  10.0
    서울   100.0  90.0
목요일 경기    50.0  50.0
    서울    50.0  50.0
수요일 경기   100.0  80.0
    서울  1000.0  90.0
월요일 경기   200.0  10.0
    부산   100.0  30.0
    서울   100.0  80.0
화요일 경기   200.0  20.0
    부산   200.0  20.0
    서울    80.0  70.0

# DataFrame의 병합과 조인

## Concat 함수로 데이터프레임 병합하기

In [199]:
# import pandas as pd
# import numpy as np

### concat 함수 사용하여 dataframe 병합하기
- `pandas.concat()` 함수
- 축을 따라 dataframe을 병합 가능
    - 기본 axis = 0 -> 행단위 병합
    - axis = 1 -> column 단위 병합

In [200]:
df1 = pd.DataFrame({'key1': np.arange(10), 'value1': np.random.randn(10)})
df2 = pd.DataFrame({'key1': np.arange(10), 'value1': np.random.randn(10)})

In [201]:
df1

   key1    value1
0     0 -0.048576
1     1 -0.918382
2     2 -0.830199
3     3  0.946116
4     4 -0.214934
5     5  0.738432
6     6 -0.461261
7     7 -0.293269
8     8  0.296926
9     9 -1.403926

In [202]:
df2

   key1    value1
0     0 -0.708746
1     1  0.379656
2     2  0.141278
3     3 -0.976487
4     4 -0.089943
5     5  0.382526
6     6 -1.644595
7     7 -0.611875
8     8 -0.458564
9     9 -1.181675

In [203]:
pd.concat([df1,df2]) # 병합을 해도 인덱스가 유지

   key1    value1
0     0 -0.048576
1     1 -0.918382
2     2 -0.830199
3     3  0.946116
4     4 -0.214934
5     5  0.738432
6     6 -0.461261
7     7 -0.293269
8     8  0.296926
9     9 -1.403926
0     0 -0.708746
1     1  0.379656
2     2  0.141278
3     3 -0.976487
4     4 -0.089943
5     5  0.382526
6     6 -1.644595
7     7 -0.611875
8     8 -0.458564
9     9 -1.181675

In [204]:
pd.concat([df1,df2], ignore_index=True) # 기존 인덱스 무시하고 새롭게 할당

    key1    value1
0      0 -0.048576
1      1 -0.918382
2      2 -0.830199
3      3  0.946116
4      4 -0.214934
5      5  0.738432
6      6 -0.461261
7      7 -0.293269
8      8  0.296926
9      9 -1.403926
10     0 -0.708746
11     1  0.379656
12     2  0.141278
13     3 -0.976487
14     4 -0.089943
15     5  0.382526
16     6 -1.644595
17     7 -0.611875
18     8 -0.458564
19     9 -1.181675

In [205]:
pd.concat([df1,df2], axis=1) # 열레벨로 concat -> 굉장히 드물게 사용

   key1    value1  key1    value1
0     0 -0.048576     0 -0.708746
1     1 -0.918382     1  0.379656
2     2 -0.830199     2  0.141278
3     3  0.946116     3 -0.976487
4     4 -0.214934     4 -0.089943
5     5  0.738432     5  0.382526
6     6 -0.461261     6 -1.644595
7     7 -0.293269     7 -0.611875
8     8  0.296926     8 -0.458564
9     9 -1.403926     9 -1.181675

- column 명이 다른 경우

In [206]:
df3 = pd.DataFrame({'key2': np.arange(10), 'value2': np.random.randn(10)})
df3

   key2    value2
0     0 -0.317208
1     1 -0.725465
2     2  0.294828
3     3  0.330196
4     4 -0.977983
5     5 -0.196398
6     6  1.716274
7     7 -0.325923
8     8  1.594132
9     9 -0.521468

In [207]:
pd.concat([df1, df3])

   key1    value1  key2    value2
0   0.0 -0.048576   NaN       NaN
1   1.0 -0.918382   NaN       NaN
2   2.0 -0.830199   NaN       NaN
3   3.0  0.946116   NaN       NaN
4   4.0 -0.214934   NaN       NaN
5   5.0  0.738432   NaN       NaN
6   6.0 -0.461261   NaN       NaN
7   7.0 -0.293269   NaN       NaN
8   8.0  0.296926   NaN       NaN
9   9.0 -1.403926   NaN       NaN
0   NaN       NaN   0.0 -0.317208
1   NaN       NaN   1.0 -0.725465
2   NaN       NaN   2.0  0.294828
3   NaN       NaN   3.0  0.330196
4   NaN       NaN   4.0 -0.977983
5   NaN       NaN   5.0 -0.196398
6   NaN       NaN   6.0  1.716274
7   NaN       NaN   7.0 -0.325923
8   NaN       NaN   8.0  1.594132
9   NaN       NaN   9.0 -0.521468

In [208]:
pd.concat([df1, df3], axis = 1)

   key1    value1  key2    value2
0     0 -0.048576     0 -0.317208
1     1 -0.918382     1 -0.725465
2     2 -0.830199     2  0.294828
3     3  0.946116     3  0.330196
4     4 -0.214934     4 -0.977983
5     5  0.738432     5 -0.196398
6     6 -0.461261     6  1.716274
7     7 -0.293269     7 -0.325923
8     8  0.296926     8  1.594132
9     9 -1.403926     9 -0.521468

## Merge, _join 함수로 데이터프레임 병합하기

### dataframe `merge`
- SQL의 join 처럼 특정한 column을 기준으로 병합
    - join 방식: `how` 파라미터를 통해 명시
        - `inner`: 파라미터의 기본값, 일치하는 값이 있는 경우
        - `left`: left outer join
        - `right`: right outer join
        - `outer`: full outer join
    - `pandas.merge` 함수가 사용됨

In [209]:
customer = pd.DataFrame({'customer_id' : np.arange(6), 
                    'name' : ['철수'"", '영희', '길동', '영수', '수민', '동건'], 
                    '나이' : [40, 20, 21, 30, 31, 18]})

customer

   customer_id name  나이
0            0   철수  40
1            1   영희  20
2            2   길동  21
3            3   영수  30
4            4   수민  31
5            5   동건  18

In [210]:
orders = pd.DataFrame({'customer_id' : [1, 1, 2, 2, 2, 3, 3, 1, 4, 9], 
                    'item' : ['치약', '칫솔', '이어폰', '헤드셋', '수건', '생수', '수건', '치약', '생수', '케이스'], 
                    'quantity' : [1, 2, 1, 1, 3, 2, 2, 3, 2, 1]})
orders.head()

   customer_id item  quantity
0            1   치약         1
1            1   칫솔         2
2            2  이어폰         1
3            2  헤드셋         1
4            2   수건         3

In [214]:
pd.merge(customer, orders, on = 'customer_id', how='inner')

   customer_id name  나이 item  quantity
0            1   영희  20   치약         1
1            1   영희  20   칫솔         2
2            1   영희  20   치약         3
3            2   길동  21  이어폰         1
4            2   길동  21  헤드셋         1
5            2   길동  21   수건         3
6            3   영수  30   생수         2
7            3   영수  30   수건         2
8            4   수민  31   생수         2

In [215]:
pd.merge(customer, orders, on = 'customer_id', how='left')

    customer_id name  나이 item  quantity
0             0   철수  40  NaN       NaN
1             1   영희  20   치약       1.0
2             1   영희  20   칫솔       2.0
3             1   영희  20   치약       3.0
4             2   길동  21  이어폰       1.0
5             2   길동  21  헤드셋       1.0
6             2   길동  21   수건       3.0
7             3   영수  30   생수       2.0
8             3   영수  30   수건       2.0
9             4   수민  31   생수       2.0
10            5   동건  18  NaN       NaN

In [216]:
pd.merge(customer, orders, on = 'customer_id', how='right')

   customer_id name    나이 item  quantity
0            1   영희  20.0   치약         1
1            1   영희  20.0   칫솔         2
2            2   길동  21.0  이어폰         1
3            2   길동  21.0  헤드셋         1
4            2   길동  21.0   수건         3
5            3   영수  30.0   생수         2
6            3   영수  30.0   수건         2
7            1   영희  20.0   치약         3
8            4   수민  31.0   생수         2
9            9  NaN   NaN  케이스         1

In [218]:
pd.merge(customer, orders, on = 'customer_id', how='outer')

    customer_id name    나이 item  quantity
0             0   철수  40.0  NaN       NaN
1             1   영희  20.0   치약       1.0
2             1   영희  20.0   칫솔       2.0
3             1   영희  20.0   치약       3.0
4             2   길동  21.0  이어폰       1.0
5             2   길동  21.0  헤드셋       1.0
6             2   길동  21.0   수건       3.0
7             3   영수  30.0   생수       2.0
8             3   영수  30.0   수건       2.0
9             4   수민  31.0   생수       2.0
10            5   동건  18.0  NaN       NaN
11            9  NaN   NaN  케이스       1.0

- index 기준으로 join 하기

In [219]:
cust1 = customer.set_index('customer_id')
order1 = orders.set_index('customer_id')

In [220]:
cust1

            name  나이
customer_id
0             철수  40
1             영희  20
2             길동  21
3             영수  30
4             수민  31
5             동건  18

In [221]:
order1

            item  quantity
customer_id
1             치약         1
1             칫솔         2
2            이어폰         1
2            헤드셋         1
2             수건         3
3             생수         2
3             수건         2
1             치약         3
4             생수         2
9            케이스         1

In [222]:
pd.merge(cust1, order1, left_index=True, right_index=True)

            name  나이 item  quantity
customer_id
1             영희  20   치약         1
1             영희  20   칫솔         2
1             영희  20   치약         3
2             길동  21  이어폰         1
2             길동  21  헤드셋         1
2             길동  21   수건         3
3             영수  30   생수         2
3             영수  30   수건         2
4             수민  31   생수         2

### 연습문제
1. 가장 많이 팔린 아이템은?
2. 영희가 가장 많이 구매한 아이템은?

In [227]:
pd.merge(customer, orders, on = 'customer_id').groupby('item').sum().sort_values(by='quantity', ascending=False)

      customer_id  name  나이  quantity
item
수건              5  길동영수  51         5
생수              7  영수수민  61         4
치약              2  영희영희  40         4
칫솔              1    영희  20         2
이어폰             2    길동  21         1
헤드셋             2    길동  21         1

In [230]:
pd.merge(customer, orders, on = 'customer_id').groupby(['name', 'item']).sum().loc['영희', 'quantity']

item
치약    4
칫솔    2
Name: quantity, dtype: int64

### join 함수
- 내부적으로 `pandas.merge` 함수 사용
- 기본적으로 index를 사용하여 left join

In [233]:
cust1.join(order1)

            name  나이 item  quantity
customer_id
0             철수  40  NaN       NaN
1             영희  20   치약       1.0
1             영희  20   칫솔       2.0
1             영희  20   치약       3.0
2             길동  21  이어폰       1.0
2             길동  21  헤드셋       1.0
2             길동  21   수건       3.0
3             영수  30   생수       2.0
3             영수  30   수건       2.0
4             수민  31   생수       2.0
5             동건  18  NaN       NaN

In [232]:
cust1.join(order1, how = 'inner')

            name  나이 item  quantity
customer_id
1             영희  20   치약         1
1             영희  20   칫솔         2
1             영희  20   치약         3
2             길동  21  이어폰         1
2             길동  21  헤드셋         1
2             길동  21   수건         3
3             영수  30   생수         2
3             영수  30   수건         2
4             수민  31   생수         2